#!/usr/bin/env python3

import os
import sys

from analyzer import Analyzer
from termcolor import colored

def main():

    # ensure proper usage
    if len(sys.argv) != 2:
        sys.exit("Usage: ./smile word")

    # absolute paths to lists   sys.path[0] is the directory containing the script that was used to invoke the Python interpreter
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")

    # instantiate analyzer (an object constructed by a class is called an instance of that class)
    analyzer = Analyzer(positives, negatives)

    # analyze word
    score = analyzer.analyze(sys.argv[1])
    if score > 0.0:
        print(colored(":)", "green"))
    elif score < 0.0:
        print(colored(":(", "red"))
    else:
        print(colored(":|", "yellow"))

if __name__ == "__main__":
    main()
